# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-service
  labels:
    app: rest-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest-service
  template:
    metadata:
      labels:
        app: rest-service
    spec:
      containers:
      - name: web-app
        image: local/rest-service:latest  # Dynamically swapped by Skaffold
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /hello-world
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          limits:
            cpu: "200m"
            memory: "128Mi"
          requests:
            cpu: "50m"
            memory: "64Mi"
